<?php

declare(strict_types=1);

namespace SoureCode\Component\Versionable\Internal\History;

/**
 * @internal Writes a `.phpstorm.meta.php` file alongside the generated
 *           `*History` / `*VersionableProxy` classes so PhpStorm and other
 *           tools that read the meta format know:
 *
 *             findByVersion(App\Entity\Post::class, ...)  → \…\PostHistory
 *             findLatestVersion(App\Entity\Post::class)    → \…\PostHistory
 *             findHistory(App\Entity\Post::class, ...)     → list<\…\PostHistory>
 *
 *           The class set is derived by scanning the cache dir for the
 *           pattern produced by {@see HistoryClassNamer::fileNameFor()} so
 *           the writer is idempotent and works whether it was invoked
 *           lazily, by cache warmup, or by the CLI command — every call
 *           rebuilds the meta file from whatever exists on disk.
 */
final class PhpStormMetaWriter
{
    public const string FILE_NAME = '.phpstorm.meta.php';
    private const string HISTORY_SUFFIX = 'History.php';

    public function write(string $cacheDir): void
    {
        if (!is_dir($cacheDir)) {
            return;
        }

        $entries = $this->scanHistoryClasses($cacheDir);
        $metaPath = $cacheDir . \DIRECTORY_SEPARATOR . self::FILE_NAME;

        if ($entries === []) {
            if (is_file($metaPath)) {
                @unlink($metaPath);
            }

            return;
        }

        file_put_contents($metaPath, $this->render($entries));
    }

    /**
     * @return array<string, string> map of original FQCN → *History FQCN
     */
    private function scanHistoryClasses(string $cacheDir): array
    {
        $entries = [];

        foreach (glob($cacheDir . \DIRECTORY_SEPARATOR . '*' . self::HISTORY_SUFFIX) ?: [] as $file) {
            $base = basename($file);

            if (str_ends_with($base, 'VersionableProxy.php')) {
                continue;
            }

            $sanitized = substr($base, 0, -strlen(self::HISTORY_SUFFIX));
            $originalClass = str_replace('_', '\\', $sanitized);
            $historyClass = HistoryClassNamer::historyClassFor($originalClass);

            $entries[$originalClass] = $historyClass;
        }

        ksort($entries);

        return $entries;
    }

    /**
     * @param array<string, string> $entries
     */
    private function render(array $entries): string
    {
        $singleMap = [];
        $listMap = [];

        foreach ($entries as $originalClass => $historyClass) {
            $originalRef = '\\' . ltrim($originalClass, '\\') . '::class';
            $historyRef = '\\' . ltrim($historyClass, '\\') . '::class';

            $singleMap[] = "        {$originalRef} => {$historyRef},";
            $listMap[] = "        {$originalRef} => '" . '\\\\' . str_replace('\\', '\\\\', ltrim($historyClass, '\\')) . "[]',";
        }

        $singleMapBlock = implode("\n", $singleMap);
        $listMapBlock = implode("\n", $listMap);

        return <<<PHP
            <?php

            declare(strict_types=1);

            // @phpstan-ignore-file
            // Auto-generated by sourecode/versionable. Do not edit; the file is
            // rewritten on every cache warmup, every CLI generate, and every
            // lazy *History/*VersionableProxy generation at runtime.

            namespace PHPSTORM_META {
                override(
                    \SoureCode\Component\Versionable\VersionerInterface::findByVersion(0),
                    map([
            {$singleMapBlock}
                    ]),
                );

                override(
                    \SoureCode\Component\Versionable\VersionerInterface::findLatestVersion(0),
                    map([
            {$singleMapBlock}
                    ]),
                );

                override(
                    \SoureCode\Component\Versionable\VersionerInterface::findHistory(0),
                    map([
            {$listMapBlock}
                    ]),
                );

                override(
                    \SoureCode\Component\Versionable\Versioner::historyClassFor(0),
                    map([
            {$singleMapBlock}
                    ]),
                );
            }

            PHP;
    }
}
